### ISSUE TITLE
Open room not being deleted after player count drops to 0

### ISSUE THREAD

**Issue by pisanovo** [Subterfuge-Revived/Remake-Backend#33]
Leaving an open room as the last player will result in an empty room. To avoid cluttering in the game browser, empty rooms should be deleted. 

https://github.com/Subterfuge-Revived/Remake-Backend/blob/ea0192bda8bc46604fd5713e8bb20be40b165232/app/Http/Controllers/RoomController.php#L260-L285

**Comment by griendt** [comment]
I agree!

Although, it would make most sense to me to introduce [soft deletes](https://laravel.com/docs/7.x/eloquent#soft-deleting) for purposes like this, so that we do have a record in the backend that the room ever existed in the first place. The benefit of Laravel's soft deletes is that you don't need to worry about accidentally querying soft-deleted records (unless you really want to).

**Comment by QuinnBast** [comment]
Should be resolved with #34
