### ISSUE TITLE
Cancel game event

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Backend#5]
We need an endpoint to cancel a game event. We would just send the session_id, room_id, and event_id to cancel the event. In the future it will need to verify that the event being cancelled is in the future but for now it doesn't have to.

**Comment by griendt** [comment]
This issue is already solved in the RESTful API: see the [`destroy` method](https://github.com/Subterfuge-Revived/Remake-Backend/blob/master/app/Http/Controllers/EventController.php#L106). An event can be destroyed if and only if it is modifiable (meaning it belongs to the given player and occurs in the future).
